import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Alert } from "@/components/ui/Alert"; import { Button } from "@/components/ui/Button"; import { Input, Label } from "@/components/ui/Form";
import { useAuth, type AuthUser } from "@/auth/AuthContext"; import { apiPost, ApiError } from "@/lib/api"; import { AuthShell } from "./AuthShell";

export default function RegisterPage() {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const { setUser } = useAuth(); const navigate = useNavigate();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { const result = await apiPost<{ user: AuthUser }>("/auth/register", { name: data.get("name"), email: data.get("email"), password: data.get("password"), acceptedTerms: data.get("terms") === "on" }); setUser(result.user); navigate("/account"); } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to create your account."); } finally { setBusy(false); } }
  return <AuthShell title="Create your account" description="Start building stronger thinking skills, one focused day at a time." path="/register" footer={<>Already have an account? <Link className="font-semibold text-[var(--color-brand-blue)]" to="/login">Sign in</Link></>}><form onSubmit={submit} className="space-y-5">{error && <Alert variant="error">{error}</Alert>}<div><Label htmlFor="name">Full name</Label><Input id="name" name="name" autoComplete="name" minLength={2} required /></div><div><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" autoComplete="email" required /></div><div><Label htmlFor="password">Password</Label><Input id="password" name="password" type="password" autoComplete="new-password" minLength={8} required /><p className="mt-1.5 text-xs text-[var(--color-ink-muted)]">Use at least 8 characters.</p></div><label className="flex items-start gap-3 text-sm text-[var(--color-ink-muted)]"><input className="mt-1" name="terms" type="checkbox" required /><span>I agree to the <Link className="text-[var(--color-brand-blue)]" to="/legal/terms">Terms</Link> and <Link className="text-[var(--color-brand-blue)]" to="/legal/privacy">Privacy Policy</Link>.</span></label><Button className="w-full" disabled={busy}>{busy ? "Creating account…" : "Create account"}</Button></form></AuthShell>;
}
