import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Link, Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthContext";
import { Seo } from "@/components/shared/Seo";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Container } from "@/components/ui/Container";
import { LoadingState } from "@/components/shared/QueryStates";
import { apiPost, apiUrl } from "@/lib/api";
const lessonTemplate = { moduleId: "", position: 1, sequenceNumber: 1, unlockDay: 1, slug: "", title: "", summary: "", estimatedMinutes: 10, passingScore: 60, content: [""], exercises: [{ prompt: "", options: ["", ""], correctIndex: 0, explanation: "" }] };
const assessmentTemplate = { slug: "", title: "", description: "", month: 1, passingScore: 60, estimatedMinutes: 20, questions: [{ prompt: "", skill: "focus", options: ["", ""], correctIndex: 0, explanation: "" }] };
export default function AdminAuthorPage() { const { user, loading } = useAuth(); const [type, setType] = useState<"lesson"|"assessment">("lesson"); const [json, setJson] = useState(JSON.stringify(lessonTemplate, null, 2)); const [note, setNote] = useState(""); const create = useMutation({ mutationFn: async () => apiPost<{ preview: unknown }>(`/admin/content/${type}`, { data: JSON.parse(json), changeNote: note }) }); if (loading) return <LoadingState label="Loading authoring workspace…" />; if (!user) return <Navigate to="/login" replace />; if (user.role !== "admin") return <Navigate to="/account" replace />; return <section className="py-12"><Seo title="Content authoring" description="Create validated learning content." path="/admin/author" /><Container className="max-w-6xl"><Link to="/admin/content" className="font-semibold text-[var(--color-brand-blue)]">← Content operations</Link><h1 className="mt-5 text-3xl font-semibold">Validated content authoring</h1><p className="mt-2 text-[var(--color-ink-muted)]">Create a draft from structured JSON. The server validates every field, records an immutable revision, and returns a learner-safe preview without answer keys.</p><label className="mt-6 block font-semibold">Content type<select className="ml-3 rounded-md border p-2" value={type} onChange={(event) => { const next = event.target.value as "lesson"|"assessment"; setType(next); setJson(JSON.stringify(next === "lesson" ? lessonTemplate : assessmentTemplate, null, 2)); }}><option value="lesson">Lesson</option><option value="assessment">Assessment</option></select></label><textarea aria-label="Content JSON" className="mt-4 min-h-[32rem] w-full rounded-md border bg-transparent p-4 font-mono text-sm" value={json} onChange={(event) => setJson(event.target.value)} /><input className="mt-3 w-full rounded-md border bg-transparent p-3" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Required revision note" /><Button className="mt-3" disabled={note.trim().length < 10 || create.isPending} onClick={() => create.mutate()}>Create validated draft</Button>{create.isError ? <Alert className="mt-4" variant="error">{create.error.message}</Alert> : null}{create.data ? <section className="surface-card mt-6 p-5"><h2 className="text-xl font-semibold">Learner-safe preview payload</h2><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(create.data.preview, null, 2)}</pre></section> : null}<p className="mt-6 text-xs text-[var(--color-ink-muted)]">API schema: {apiUrl(`/admin/content/${type}`)}</p></Container></section>; }
