import { useQuery } from "@tanstack/react-query";
import { Link, Navigate } from "react-router-dom";
import { Activity, CreditCard, KeyRound, MailWarning, Users } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { Alert } from "@/components/ui/Alert";
import { Container } from "@/components/ui/Container";
import { LoadingState } from "@/components/shared/QueryStates";
import { Seo } from "@/components/shared/Seo";
import { apiGet } from "@/lib/api";

type Dashboard = { summary: { users: number; activeEntitlements: number; pendingOrders: number; failedWebhooks: number; failedCertificateEmails: number }; recentOrders: Array<{ _id: string; customerName: string; customerEmail: string; amount: number; currency: string; status: string; createdAt: string }>; recentAudits: Array<{ _id: string; action: string; targetType: string; targetId: string; createdAt: string; actorUserId?: { name: string; email: string } }> };
const cards = [{ key: "users", label: "Users", icon: Users }, { key: "activeEntitlements", label: "Active access", icon: KeyRound }, { key: "pendingOrders", label: "Pending orders", icon: CreditCard }, { key: "failedWebhooks", label: "Failed webhooks", icon: Activity }, { key: "failedCertificateEmails", label: "Failed certificate emails", icon: MailWarning }] as const;

export default function AdminDashboardPage() {
  const { user, loading } = useAuth();
  const dashboard = useQuery({ queryKey: ["admin-dashboard"], queryFn: () => apiGet<Dashboard>("/admin/dashboard"), enabled: user?.role === "admin", retry: false });
  if (loading) return <LoadingState label="Loading administrator dashboard…" />;
  if (!user) return <Navigate to="/login" state={{ from: "/admin" }} replace />;
  if (user.role !== "admin") return <Navigate to="/account" replace />;
  return <section className="py-12 sm:py-20"><Seo title="Administrator dashboard" description="CogniSprint operational overview." path="/admin" /><Container className="max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Administration</p><h1 className="mt-3 text-3xl font-semibold">Operations dashboard</h1><p className="mt-2 text-[var(--color-ink-muted)]">Signed in as {user.email}</p></div><Link to="/admin/certificates" className="font-semibold text-[var(--color-brand-blue)]">Manage certificates →</Link></div>{dashboard.isLoading ? <LoadingState label="Loading operations…" /> : null}{dashboard.isError ? <Alert className="mt-8" variant="error">The administrator dashboard could not be loaded.</Alert> : null}{dashboard.data ? <><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(({ key, label, icon: Icon }) => <article className="surface-card p-5" key={key}><Icon className="h-5 w-5 text-[var(--color-brand-blue)]" /><p className="mt-3 text-2xl font-semibold">{dashboard.data.summary[key]}</p><p className="text-sm text-[var(--color-ink-muted)]">{label}</p></article>)}</div><section className="surface-card mt-8 overflow-x-auto p-6"><h2 className="text-xl font-semibold">Recent orders</h2><table className="mt-4 w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b"><th className="py-3">Customer</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>{dashboard.data.recentOrders.map((order) => <tr className="border-b last:border-0" key={order._id}><td className="py-3"><strong>{order.customerName}</strong><br /><span className="text-[var(--color-ink-muted)]">{order.customerEmail}</span></td><td className="capitalize">{order.status}</td><td>{order.currency} {(order.amount / 100).toFixed(2)}</td><td>{new Date(order.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section><section className="surface-card mt-8 p-6"><h2 className="text-xl font-semibold">Recent audited actions</h2><div className="mt-4 space-y-3">{dashboard.data.recentAudits.map((audit) => <article className="rounded-[var(--radius-md)] border p-3 text-sm" key={audit._id}><strong>{audit.action}</strong> · {audit.targetType} {audit.targetId}<br /><span className="text-[var(--color-ink-muted)]">{audit.actorUserId?.email ?? "Unknown actor"} · {new Date(audit.createdAt).toLocaleString()}</span></article>)}{!dashboard.data.recentAudits.length ? <p className="text-sm text-[var(--color-ink-muted)]">No administrator mutations recorded yet.</p> : null}</div></section></> : null}</Container></section>;
}
